-- MySQL Script generated by MySQL Workbench
-- 05/12/16 13:31:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema negocio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema negocio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `negocio` DEFAULT CHARACTER SET utf8 ;
USE `negocio` ;

-- -----------------------------------------------------
-- Table `negocio`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Genero` (
  `idGenero` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(20) NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Provincia` (
  `idProvincia` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`idProvincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Localidad` (
  `idLocalidad` INT NOT NULL AUTO_INCREMENT,
  `idProvincia` INT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idLocalidad`),
  INDEX `fkProvinciaLocalidad_idx` (`idProvincia` ASC),
  CONSTRAINT `fkProvinciaLocalidad`
    FOREIGN KEY (`idProvincia`)
    REFERENCES `negocio`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `idLocalidad` INT NULL,
  `direccion` VARCHAR(45) NULL,
  `cp` INT NULL,
  PRIMARY KEY (`idDireccion`),
  INDEX `fkLocalidad_idx` (`idLocalidad` ASC),
  CONSTRAINT `fkLocalidad`
    FOREIGN KEY (`idLocalidad`)
    REFERENCES `negocio`.`Localidad` (`idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `numDni` INT NULL,
  `tipoDni` VARCHAR(10) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `idGenero` INT NULL,
  `fechaNacimiento` DATE NULL,
  `idDireccion` INT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `idGenero_idx` (`idGenero` ASC),
  INDEX `fkDireccion_idx` (`idDireccion` ASC),
  CONSTRAINT `fkGenero`
    FOREIGN KEY (`idGenero`)
    REFERENCES `negocio`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkDireccion`
    FOREIGN KEY (`idDireccion`)
    REFERENCES `negocio`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `idPersona` INT NULL,
  `habilitado` TINYINT(1) NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fkPersona_idx` (`idPersona` ASC),
  CONSTRAINT `fkPersona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `negocio`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NULL,
  `reputacion` INT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `idUsuario_idx` (`idUsuario` ASC),
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `negocio`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Cupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Cupon` (
  `idCupon` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `montoDescuento` FLOAT NULL,
  PRIMARY KEY (`idCupon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Compra` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NULL,
  `idCupon` INT NULL,
  `monto` DOUBLE NULL,
  `fechaCompra` DATE NULL,
  `fechaPago` DATE NULL,
  `estado` VARCHAR(45) NULL,
  `Compracol` VARCHAR(45) NULL,
  PRIMARY KEY (`idCompra`),
  INDEX `fkCliente2_idx` (`idCliente` ASC),
  INDEX `fkCupon4_idx` (`idCupon` ASC),
  CONSTRAINT `fkCliente2`
    FOREIGN KEY (`idCliente`)
    REFERENCES `negocio`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkCupon4`
    FOREIGN KEY (`idCupon`)
    REFERENCES `negocio`.`Cupon` (`idCupon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `idCategoria` INT NULL,
  `idGenero` INT NULL,
  `titulo` VARCHAR(45) NULL,
  `precio` DOUBLE NULL,
  `descripcion` VARCHAR(500) NULL,
  `puntoReposicion` INT NULL,
  `urlImagen` VARCHAR(250) NULL,
  `urlImagenAlt1` VARCHAR(250) NULL,
  `urlImagenAlt2` VARCHAR(250) NULL,
  `urlImagenAlt3` VARCHAR(250) NULL,
  `baja` TINYINT(1) NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `idCategoria_idx` (`idCategoria` ASC),
  INDEX `fkGenero_idx` (`idGenero` ASC),
  CONSTRAINT `idCategoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `negocio`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkGenero3`
    FOREIGN KEY (`idGenero`)
    REFERENCES `negocio`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Talle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Talle` (
  `idTalle` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idTalle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Color` (
  `idColor` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idColor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`PresentacionProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`PresentacionProducto` (
  `codSku` INT NOT NULL AUTO_INCREMENT,
  `idProducto` INT NULL,
  `idTalle` INT NULL,
  `idColor` INT NULL,
  INDEX `fkProducto5_idx` (`idProducto` ASC),
  INDEX `fkTalle4_idx` (`idTalle` ASC),
  INDEX `fkColor4_idx` (`idColor` ASC),
  PRIMARY KEY (`codSku`),
  CONSTRAINT `fkPProducto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `negocio`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkPPTalle`
    FOREIGN KEY (`idTalle`)
    REFERENCES `negocio`.`Talle` (`idTalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkPPColor`
    FOREIGN KEY (`idColor`)
    REFERENCES `negocio`.`Color` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`DetalleCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`DetalleCompra` (
  `idCompra` INT NOT NULL,
  `codSku` INT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`idCompra`),
  INDEX `fk_DetalleCompra_1_idx` (`codSku` ASC),
  CONSTRAINT `idCompra`
    FOREIGN KEY (`idCompra`)
    REFERENCES `negocio`.`Compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleCompra_1`
    FOREIGN KEY (`codSku`)
    REFERENCES `negocio`.`PresentacionProducto` (`codSku`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Precio_Mp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Precio_Mp` (
  `idPrecio` INT NOT NULL AUTO_INCREMENT,
  `precio` DOUBLE NULL,
  `unidad` DOUBLE NULL,
  PRIMARY KEY (`idPrecio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`MP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`MP` (
  `idMP` INT NOT NULL AUTO_INCREMENT,
  `idPrecio` INT NULL,
  `titulo` VARCHAR(45) NULL,
  `medida` VARCHAR(45) NULL,
  `stock` INT NULL,
  `puntoReposicion` INT NULL,
  `baja` TINYINT(1) NULL,
  PRIMARY KEY (`idMP`),
  INDEX `idPrecio_idx` (`idPrecio` ASC),
  CONSTRAINT `idPrecio`
    FOREIGN KEY (`idPrecio`)
    REFERENCES `negocio`.`Precio_Mp` (`idPrecio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Prod_MP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Prod_MP` (
  `idProducto` INT NULL,
  `idMP` INT NULL,
  `cantidad` INT NULL,
  INDEX `idMp_idx` (`idMP` ASC),
  CONSTRAINT `fkProducto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `negocio`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkMp`
    FOREIGN KEY (`idMP`)
    REFERENCES `negocio`.`MP` (`idMP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NULL,
  `puesto` VARCHAR(45) NULL,
  `baja` TINYINT(1) NULL,
  `Empleadocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpleado`),
  INDEX `idUsuario_idx` (`idUsuario` ASC),
  CONSTRAINT `fkUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `negocio`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Sucursal` (
  `idSucursal` INT NOT NULL AUTO_INCREMENT,
  `idDireccion` INT NULL,
  `nroSucursal` INT NULL,
  `telefono` VARCHAR(45) NULL,
  `horarioAtencion` VARCHAR(100) NULL,
  PRIMARY KEY (`idSucursal`),
  INDEX `fkDireccion_idx` (`idDireccion` ASC),
  CONSTRAINT `fkDireccion2`
    FOREIGN KEY (`idDireccion`)
    REFERENCES `negocio`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Stock_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Stock_Producto` (
  `idStock` INT NOT NULL AUTO_INCREMENT,
  `codSku` INT NULL,
  `idSucursal` INT NULL,
  `cantidad` INT NULL,
  INDEX `idSucursal_idx` (`idSucursal` ASC),
  PRIMARY KEY (`idStock`),
  INDEX `fkSku_idx` (`codSku` ASC),
  CONSTRAINT `fkSucursal`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `negocio`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkSku`
    FOREIGN KEY (`codSku`)
    REFERENCES `negocio`.`PresentacionProducto` (`codSku`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`AvisoProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`AvisoProducto` (
  `idAvisoProducto` INT NOT NULL AUTO_INCREMENT,
  `idStock` INT NULL,
  `fecha` DATE NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idAvisoProducto`),
  INDEX `fkStock_idx` (`idStock` ASC),
  CONSTRAINT `fkStock`
    FOREIGN KEY (`idStock`)
    REFERENCES `negocio`.`Stock_Producto` (`idStock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`AvisoMp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`AvisoMp` (
  `idAvisoMp` INT NOT NULL AUTO_INCREMENT,
  `idMp` INT NULL,
  `fecha` DATE NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idAvisoMp`),
  INDEX `IdMp_idx` (`idMp` ASC),
  CONSTRAINT `IdMp`
    FOREIGN KEY (`idMp`)
    REFERENCES `negocio`.`MP` (`idMP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`EnvioSucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`EnvioSucursal` (
  `idEnvioSucursal` INT NOT NULL AUTO_INCREMENT,
  `idSucursal1` INT NOT NULL,
  `idSucursal2` INT NOT NULL,
  `tardanza` INT NULL,
  INDEX `idSucursal1_idx` (`idSucursal1` ASC),
  INDEX `idSucursal2_idx` (`idSucursal2` ASC),
  PRIMARY KEY (`idEnvioSucursal`),
  CONSTRAINT `idSucursal1`
    FOREIGN KEY (`idSucursal1`)
    REFERENCES `negocio`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idSucursal2`
    FOREIGN KEY (`idSucursal2`)
    REFERENCES `negocio`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Lugar` (
  `idLugar` INT NOT NULL AUTO_INCREMENT,
  `idLocalidad` INT NULL,
  `tardanzaDias` INT NULL,
  `costo` DOUBLE NULL,
  PRIMARY KEY (`idLugar`),
  INDEX `fk2Localidad_idx` (`idLocalidad` ASC),
  CONSTRAINT `fk2Localidad`
    FOREIGN KEY (`idLocalidad`)
    REFERENCES `negocio`.`Localidad` (`idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`PedidoProveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`PedidoProveedor` (
  `idPedidoProveedor` INT NOT NULL AUTO_INCREMENT,
  `monto` FLOAT NULL,
  `fechaPedido` DATE NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idPedidoProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Pedido_Mp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Pedido_Mp` (
  `idPedidoProveedor` INT NULL,
  `idMp` INT NULL,
  `cantidad` VARCHAR(45) NULL,
  INDEX `fkPedidoProovedor_idx` (`idPedidoProveedor` ASC),
  INDEX `fkMp_idx` (`idMp` ASC),
  CONSTRAINT `fkPedidoProovedor`
    FOREIGN KEY (`idPedidoProveedor`)
    REFERENCES `negocio`.`PedidoProveedor` (`idPedidoProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkMp2`
    FOREIGN KEY (`idMp`)
    REFERENCES `negocio`.`MP` (`idMP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`CuponCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`CuponCliente` (
  `idCupon` INT NULL,
  `idCliente` INT NULL,
  `estado` VARCHAR(45) NULL,
  INDEX `fkCupon2_idx` (`idCupon` ASC),
  INDEX `fkCliente3_idx` (`idCliente` ASC),
  CONSTRAINT `fkCupon2`
    FOREIGN KEY (`idCupon`)
    REFERENCES `negocio`.`Cupon` (`idCupon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkCliente3`
    FOREIGN KEY (`idCliente`)
    REFERENCES `negocio`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Banco` (
  `idBanco` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`idBanco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Tarjeta` (
  `idTarjeta` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`idTarjeta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`TarjetaBanco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`TarjetaBanco` (
  `idTarjeta` INT NULL,
  `idBanco` INT NULL,
  `cuotas` INT NULL,
  `interes` INT NULL,
  INDEX `fkTarjetaBanco1_idx` (`idBanco` ASC),
  INDEX `fkTarjetaBanco2_idx` (`idTarjeta` ASC),
  CONSTRAINT `fkTarjetaBanco1`
    FOREIGN KEY (`idBanco`)
    REFERENCES `negocio`.`Banco` (`idBanco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkTarjetaBanco2`
    FOREIGN KEY (`idTarjeta`)
    REFERENCES `negocio`.`Tarjeta` (`idTarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `negocio`.`Imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `negocio`.`Imagenes` (
  `idImagenes` VARCHAR(500) NOT NULL,
  `carrusel1` VARCHAR(500) NULL,
  `carrusel2` VARCHAR(500) NULL,
  `carrusel3` VARCHAR(500) NULL,
  `carrusel4` VARCHAR(500) NULL,
  `bannerIzq` VARCHAR(500) NULL,
  `bannerDer` VARCHAR(500) NULL,
  `modulo` VARCHAR(500) NULL,
  PRIMARY KEY (`idImagenes`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
